version: '3.9'

services:

    api_database:
        image: ${DATABASE_DRIVER}:${DATABASE_VERSION}
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - api-postgres-data:/var/lib/postgresql/data
        ports:
            - ${DATABASE_PORTS}
        networks:
            - api-network

    api_database_test:
        image: ${DATABASE_DRIVER}:${DATABASE_VERSION}
        environment:
            POSTGRES_DB: ${TEST_DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - api-postgres-data-test:/var/lib/postgresql/data
        ports:
            - ${TEST_DATABASE_PORTS}
        networks:
            - api-network

    api_php:
        build:
            context: ./docker/php
            args:
                UID: ${UID}
                DEVELOPER_EMAIL: ${DEVELOPER_EMAIL}
                DEVELOPER_NAME: ${DEVELOPER_NAME}
                ENABLE_PHP_XDEBUG: ${ENABLE_PHP_XDEBUG}
        ports:
            - ${FPM_PORTS}
        volumes:
            - .:/var/app/current:cached
            - ./var/log:/var/log:cached
        depends_on:
            - api_database
        networks:
            - api-network

    api_server:
        build:
            context: ./docker/server/${SERVER_NAME}
            args:
                UID: ${UID}
        ports:
            - ${SERVER_PORTS}
            - ${SERVER_PORTS_TLS}
        volumes:
            - .:/var/app/current:cached
            - ./var/log:/var/log/nginx:cached
        depends_on:
            - api_php
        networks:
            - api-network

volumes:
    api-postgres-data:
    api-postgres-data-test:

networks:
    api-network: